language: julia
os:
    - linux
julia:
    - 1.0
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
dist: trusty

install:
  - pip --version
  - pip install --user --upgrade pip

addons:
    apt_packages:
        - gfortran
        - qt5-default
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("HydroPowerModels")'
    - julia -e 'Pkg.test("HydroPowerModels"; coverage=true)'
after_success:
    # push coverage results to Codecov
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'cd(Pkg.dir("HydroPowerModels")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'cd(Pkg.dir("HydroPowerModels")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
